CREATE DATABASE QuanLySinhVien;

USE QUANLYSINHVIEN;

CREATE TABLE ACCOUNT(
	AID NVARCHAR(10) PRIMARY KEY,
	USERNAME NVARCHAR(10) NOT NULL,
	PASSWORD  NVARCHAR(10) NOT NULL,
	PERMISSION INT DEFAULT 1, -- 0: Admin 1: Sinh Vien 2: Giang Vien
	CREATE_DATE DATE
);

CREATE TABLE FACULTY(
	FID NVARCHAR(10) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE STUDENT(
	SID NVARCHAR(10) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	GENDER BIT NOT NULL,
	DATEOFBIRTH DATE NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	PHONE NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NOT NULL,
	AID NVARCHAR(10) NOT NULL,
	FID NVARCHAR(10) NOT NULL,
	FOREIGN KEY (AID) REFERENCES ACCOUNT(AID),
	FOREIGN KEY (FID) REFERENCES FACULTY(FID)
);

CREATE TABLE COURSE(
	CID NVARCHAR(10) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	DESCRIPTION NVARCHAR(100) NOT NULL
);

CREATE TABLE COURSE_CLASS(
	CID NVARCHAR(10) NOT NULL,
	CCID NVARCHAR(10) PRIMARY KEY,
	SECTION NVARCHAR(10) NOT NULL,
	SEMESTER NVARCHAR(50) NOT NULL,
	DESCRIPTION NVARCHAR(100) NOT NULL,
	FOREIGN KEY (CID) REFERENCES COURSE(CID)
);

CREATE TABLE TRANSCRIPT(
	CCID NVARCHAR(10) NOT NULL,
	SID NVARCHAR(10) NOT NULL,
	SCORE NVARCHAR(5) NOT NULL,
	SEMESTER NVARCHAR(50) NOT NULL,
	STATUS BIT DEFAULT 1, -- 1. Mo 0. Dong
	PRIMARY KEY (CCID, SID),
	FOREIGN KEY (CCID) REFERENCES COURSE_CLASS(CCID),
	FOREIGN KEY (SID) REFERENCES STUDENT(SID)
);

CREATE TABLE TEACHER(
	TID NVARCHAR(10) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	PHONE NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NOT NULL,
	AID NVARCHAR(10) NOT NULL,
	FOREIGN KEY (AID) REFERENCES ACCOUNT(AID)
);

CREATE TABLE TEACHING_CLASS(
	TID NVARCHAR(10) NOT NULL,
	CCID NVARCHAR(10) NOT NULL,
	SEMESTER NVARCHAR(50) NOT NULL,
	FOREIGN KEY (CCID) REFERENCES COURSE_CLASS(CCID),
	FOREIGN KEY (TID) REFERENCES TEACHER(TID)
);

CREATE TABLE ADMIN(
	ID NVARCHAR(10) PRIMARY KEY,
	NAME NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	PHONE NVARCHAR(50) NOT NULL,
	ADDRESS NVARCHAR(100) NOT NULL,
	AID NVARCHAR(10) NOT NULL,
	FOREIGN KEY (AID) REFERENCES ACCOUNT(AID)
);

INSERT INTO ACCOUNT VALUES(N'01', N'admin', N'12345', 0, NOW());
INSERT INTO ACCOUNT VALUES(N'02', N'student', N'12345', 1, NOW());
INSERT INTO ACCOUNT VALUES(N'03', N'teacher', N'12345', 2, NOW());
INSERT INTO ACCOUNT VALUES(N'04', N'teacher1', N'12345', 2, NOW());
INSERT INTO ACCOUNT VALUES(N'05', N'teacher2', N'12345', 2, NOW());
INSERT INTO ACCOUNT VALUES(N'06', N'teacher3', N'12345', 2, NOW());
INSERT INTO ACCOUNT VALUES(N'07', N'teacher4', N'12345', 2, NOW());
INSERT INTO ACCOUNT VALUES(N'08', N'teacher5', N'12345', 2, NOW());
INSERT INTO ACCOUNT VALUES(N'09', N'teacher6', N'12345', 2, NOW());

INSERT INTO TEACHER VALUES(N'01', N'Ngô Hiếu Thảo', N'thao1222@gmail.com', N'085395330', 'HCM', '02');
INSERT INTO TEACHER VALUES(N'02', N'Ngô Trà My', N'tramy1999@gmail.com', N'093243430', 'HCM', '04');
INSERT INTO TEACHER VALUES(N'03', N'Định Thi Thiên', N'thien1901@gmail.com', N'02434330', 'HCM', '05');
INSERT INTO TEACHER VALUES(N'04', N'Huỳnh Chí Hữu', N'laohy12@gmail.com', N'04234330', 'HCM', '06');
INSERT INTO TEACHER VALUES(N'05', N'Lê Gia Lộc', N'locxza@gmail.com', N'053595330', 'HCM', '07');
INSERT INTO TEACHER VALUES(N'06', N'Nguyễn Trung', N'trungtrung12@gmail.com', N'054395330', 'HCM', '08');
INSERT INTO TEACHER VALUES(N'07', N'Nguyễn Trung  Khánh Ka', N'trungka@gmail.com', N'08594533', 'HCM', '09');
